// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI agent that generates daily horoscopes.
 *
 * - dailyHoroscope - A function that generates a daily horoscope for a given zodiac sign.
 * - DailyHoroscopeInput - The input type for the dailyHoroscope function.
 * - DailyHoroscopeOutput - The return type for the dailyHoroscope function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DailyHoroscopeInputSchema = z.object({
  zodiacSign: z
    .string()
    .describe('The zodiac sign for which to generate the horoscope.'),
});
export type DailyHoroscopeInput = z.infer<typeof DailyHoroscopeInputSchema>;

const DailyHoroscopeOutputSchema = z.object({
  horoscope: z.string().describe('The generated daily horoscope text.'),
});
export type DailyHoroscopeOutput = z.infer<typeof DailyHoroscopeOutputSchema>;

export async function dailyHoroscope(input: DailyHoroscopeInput): Promise<DailyHoroscopeOutput> {
  return dailyHoroscopeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'dailyHoroscopePrompt',
  input: {schema: DailyHoroscopeInputSchema},
  output: {schema: DailyHoroscopeOutputSchema},
  prompt: `You are a mystical and insightful astrologer.

Generate a daily horoscope for the zodiac sign: {{{zodiacSign}}}.

The horoscope should be about 3-4 sentences long and cover themes like love, career, and personal growth in an encouraging and positive tone. Do not add any titles or headers.
`,
});

const dailyHoroscopeFlow = ai.defineFlow(
  {
    name: 'dailyHoroscopeFlow',
    inputSchema: DailyHoroscopeInputSchema,
    outputSchema: DailyHoroscopeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
