// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI agent that matches users with astrologers based on their queries.
 *
 * - astrologerMatchmaking - A function that processes user queries and recommends astrologers.
 * - AstrologerMatchmakingInput - The input type for the astrologerMatchmaking function.
 * - AstrologerMatchmakingOutput - The return type for the astrologerMatchmaking function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AstrologerMatchmakingInputSchema = z.object({
  query: z
    .string()
    .describe('The user query about astrology.'),
});
export type AstrologerMatchmakingInput = z.infer<typeof AstrologerMatchmakingInputSchema>;

const AstrologerMatchmakingOutputSchema = z.object({
  recommendedAstrologers: z
    .array(z.string())
    .describe('A list of recommended astrologers with expertise in the user query.'),
  reasoning: z.string().describe('The AI reasoning for recommending these astrologers.'),
});
export type AstrologerMatchmakingOutput = z.infer<typeof AstrologerMatchmakingOutputSchema>;

export async function astrologerMatchmaking(input: AstrologerMatchmakingInput): Promise<AstrologerMatchmakingOutput> {
  return astrologerMatchmakingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'astrologerMatchmakingPrompt',
  input: {schema: AstrologerMatchmakingInputSchema},
  output: {schema: AstrologerMatchmakingOutputSchema},
  prompt: `You are an AI astrologer matchmaking assistant.

You will take the user's query and return a list of astrologers that are best suited to answer the user's question.

User Query: {{{query}}}

Return a list of astrologers with expertise in the user query, and a reasoning for recommending these astrologers.
`,
});

const astrologerMatchmakingFlow = ai.defineFlow(
  {
    name: 'astrologerMatchmakingFlow',
    inputSchema: AstrologerMatchmakingInputSchema,
    outputSchema: AstrologerMatchmakingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
